
# training pipline config:
training_pipeline_config:
  pipeline_name: banking
  root_artifact_dir: artifact

# data ingestion config
data_ingestion_config:
  dataset_download_url: https://archive.ics.uci.edu/ml/machine-learning-databases/00522/SouthGermanCredit.zip
  zip_download_dir: zip_data
  extracted_data_dir: extracted_data
  raw_data_dir: raw_data
  ingested_data_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir:  test
  
# data validation config
data_validation_config:
  schema_file_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

# data transformation config
data_transformation_config:
  transformed_data_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessed_model_dir: preprocessed_model
  preprocessed_model_object_file_name: preprocessed_model.pkl

  
# model trainer config
model_trainer_config:
  trained_model_dir: trained_model
  trained_model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: config
  model_config_file_name: model_config.yaml


# model evaluation config
model_evaluation_config:
  model_evaluation_report_file_name: "model_evaluation_report.yaml"


# model pusher config
model_pusher_config:
  export_model_dir: saved_models
# experiment config:
experiment_config:
  experiment_dir: 'experiment'
  experiment_file_name: 'experiment.csv'

  