# training pipline config:
training_pipeline_config:
  pipeline_name: banking
  root_artifact_dir: artifact

# data ingestion config
data_ingestion_config:
  dataset_download_url: https://archive.ics.uci.edu/ml/machine-learning-databases/00522/SouthGermanCredit.zip
  zip_download_dir: zip_data
  extracted_data_dir: extracted_data
  raw_data_dir: raw_data
  ingested_data_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir:  test
  
# data validation config
data_validation_config:
  schema_file_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

# data transformation config
data_transformation_config:
  transformed_data_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessed_model_dir: preprocessed_model
  preprocessed_model_object_file_name: preprocessed_model.pkl

  
