grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 7
    verbose: 2
model_selection:
  model_0:
    class: LogisticRegression
    grid_search_params:
      fit_intercept:
      - true
      - false
    model_1:
      class: RandomForestClassifier
      grid_search_params:
        criterion:
        - gini
        - entropy
        min_sample_leaf:
        - 1
        - 2
      module: sklearn.ensemble
      params:
        min_sample_leaf: 2
    module: sklearn.linear_model
    params:
      solver: liblinear
