columns:
  alter:
    - age
    - int
  beruf:
    - job
    - int
  beszeit:
    - employment_duration
    - int
  bishkred:
    - number_credits
    - int
  buerge:
    - other_debtors
    - int
  famges:
    - personal_status_sex
    - int
  gastarb:
    - foreign_worker
    - int
  hoehe:
    - amount
    - int
  kredit:
    - credit_risk
    - int
  laufkont:
    - status
    - int
  laufzeit:
    - duration
    - int
  moral:
    - credit_history
    - int
  pers:
    - people_liable
    - int
  rate:
    - installment_rate
    - int
  sparkont:
    - savings
    - int
  telef:
    - telephone
    - int
  verm:
    - property
    - int
  verw:
    - purpose
    - int
  weitkred:
    - other_installment_plans
    - int
  wohn:
    - housing
    - int
  wohnzeit:
    - present_residence
    - int


target_column: credit_risk


continuous_column:
  - age
  - amount
  - duration 


domain_value:
  laufkont:
    - 1
    - 2
    - 3
    - 4
  moral:
    - 0
    - 1
    - 2
    - 3
    - 4 
  verw:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  sparkont:
    - 1
    - 2
    - 3
    - 4
    - 5
  beszeit:
    - 1
    - 2
    - 3
    - 4
    - 5
  rate:
    - 1
    - 2
    - 3
    - 4
  famges:
    - 1
    - 2
    - 3
    - 4
  buerge:
    - 1
    - 2
    - 3
  wohnzeit:
    - 1
    - 2
    - 3
    - 4
  verm:
    - 1
    - 2
    - 3
    - 4
  weitkred:
    - 1
    - 2
    - 3
  wohn:
    - 1
    - 2
    - 3
  bishkred:
    - 1
    - 2
    - 3
    - 4
  beruf:
    - 1
    - 2
    - 3
    - 4
  pers:
    - 1
    - 2
  telef:
    - 1
    - 2
  gastarb:
    - 1
    - 2
  kredit:
    - 0
    - 1